### PR TITLE
Dark mode feature added

### PR DESCRIPTION
**Pull request by Faisalhs51**
Feature: #14

Dark mode added.
It is responsive also.

### CODE REVIEW

**Comment by Faisalhs51** [comment]
Also Fixes: #21

**Comment by omrajsharma** [comment]
feature looks fine Faisal, just minor color changes required I'm listing down below.

Color of classes in dark mode
.item-card { color: #494949 }
.img-card-price { color: #efefef }
.img-card-title, .img-card-location, .img-card-footer { color: #a7a7a7 }
.footer-container { background-color: #494949 }

.profile-ad-item { background: #494949 } 
.profile-ad-item-header { color: #efefef }
.profile-ad-item-location, .profile-ad-item-price-type { color: #a7a7a7 }

Also you can remove dark mode toggle button from profile

**Comment by omrajsharma** [comment]
Please resolve the conflict, let me know if you need any help.

**Comment by Faisalhs51** [comment]
Done with all the changes as you said
Scroll to top is not displaying properly in earlier commit, but now its working fine.

**Pull request merged**
