### PR TITLE
Added the button to scroll to the top 

### PR DESCRIPTION
**Pull request by ahmohil**
I have made a PR. 

- Created a separate component and added that to the MainLayout
If you want any change I am open for feedback.

### CODE REVIEW

**Comment by omrajsharma** [comment]
Screenshot 2023-09-08 at 8 05 34 AM
In small screens the "to the top button" is hidden behind the bottom nav bar. Can you please verify that as well.

**Comment by ahmohil** [comment]
Yes, you are right. I'll change the code to make sure that the button is visible on smaller screens as well.

**Comment by ahmohil** [comment]
- The button is now visible for smaller screens.

https://github.com/omrajsharma/awaas-vishwa-fe/assets/53046043/c3acdc6a-3e20-4885-859c-29da5937a8ba

**Comment by omrajsharma** [comment]
I've merged your PR, thanks for contributing.

**Pull request merged**
